test1-2 commit
bbowl/AJS_NK pull request #1
Opened 2024-03-30 13:08 UTC by bbowl

added tests
- Test 1 - Perform Login
- Test 2 - Add product to the cart

2024-03-30 21:21 UTC, hlazkov commented on tests/test1-2.spec.js
> +  await expect(page.locator("//span[@data-test='shopping-cart-badge'][text()='1']")).toBeVisible();
1. Its better to check if `shopping-cart-badge` has text `1` explicitly
2. Its better to use CSS or xpath selectors through whole project, not mixing it.

2024-03-30 21:22 UTC, hlazkov commented on tests/test1-2.spec.js
> +  await expect(page.locator("//div[@data-test='inventory-item'][1]")).toBeVisible();
Same here, lets use CSS selector instead

2024-03-30 21:22 UTC, hlazkov requested changes
Looks nice, but recheck on comments please!

2024-04-04 19:44 UTC, AlinaZhykharieva commented
great job! that is nice you`ve changed all locators to Xpath, but here almost always we have class or id for element, so CSS will be preferable from my POV. But it is your decision if you will have time you can try it with CSS.

2024-04-04 19:45 UTC, AlinaZhykharieva approved these changes

2024-04-05 09:37 UTC, merged